#!/usr/bin/env bash
#
# Yet another minimal TOTP generator
#
#/ Usage:
#/   ./totp <secret>

mac=$(printf %016X "$(( ($(date +%s)) / 30))" \
    | xxd -r -p \
    | openssl sha1 -hmac "$(base32 -d <<< "${1^^}")" \
    | cut -d' ' -f2)
offset="$(( 16#"${mac:39:1}" * 2))"
printf '%06d\n' "$(( (0x${mac:offset:8} & 0x7FFFFFFF) % 1000000 ))"
